// dart format off
// coverage:ignore-file
// ignore_for_file: constant_identifier_names
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************

abstract final class Assets {
  /// {@macro assets_generator.img_auto_angle_jpg.preview}
  static const String img_auto_angle_jpg = 'img/auto-angle.jpg';

  /// {@macro assets_generator.img_have_exif_jpg.preview}
  static const String img_have_exif_jpg = 'img/have-exif.jpg';

  /// {@macro assets_generator.img_header_png.preview}
  static const String img_header_png = 'img/header.png';

  /// {@macro assets_generator.img_icon_webp.preview}
  static const String img_icon_webp = 'img/icon.webp';

  /// {@macro assets_generator.img_img_jpg.preview}
  static const String img_img_jpg = 'img/img.jpg';

  /// {@macro assets_generator.img_transparent_background_png.preview}
  static const String img_transparent_background_png =
      'img/transparent-background.png';
}
