name: Runnable (stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: flutter pub get
      - name: Get melos
        run: dart pub global activate melos
      - name: Init melos
        run: |
          melos bootstrap
          melos run get
      - name: Analyze
        run: melos run analyze
  test_iOS:
    needs: analyze
    name: Test iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - name: Get melos
        run: dart pub global activate melos
      - name: Init melos
        run: |
          melos bootstrap
          melos run get
      - name: Build iOS debug with melos
        run: melos run try_build_ios 

  test_android:
    needs: analyze
    name: Test Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: sudo echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.4.7075529"
      - name: Get melos
        run: dart pub global activate melos
      - name: Init melos
        run: |
          melos bootstrap
          melos run get
      - run: melos run try_build_apk
